version: '3.8'

services:
  db:
    image: postgres:13
    container_name: spring_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456a
      POSTGRES_DB: e-commerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: ecommerce_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/e-commerce
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456a
    ports:
      - "8080:8080"

volumes:
  postgres_data: